// Training data for IST with 9 types of subtest questions
// Each type has 5 rational but not difficult questions

export const trainingData = {
    id: "training",
    name: "Latihan IST",
    description: "Halaman Latihan IST",
    timeLimit: 5, // 5 minutes
  };
  
  // Type definitions for training questions
  export interface TrainingOption {
    id: string;
    questionId: string;
    text: string | null;
    imageUrl: string | null;
    label: string;
  }
  
  export interface TrainingQuestion {
    id: string;
    subtestTemplateId: string;
    text: string | null;
    options?: TrainingOption[];
    imageUrl?: string;
    createdAt: Date;
    updatedAt: Date;
    correctAnswer?: string | null;
    order: number;
    question: string; // always present
  }
  
  export const getTrainingQuestions = (type: string): TrainingQuestion[] => {
    switch (type) {
      case "1":
        // Subtest 1: Analogi Verbal (Radio Questions)
        return [
          {
            id: "train-1-1",
            text: "Pilih kata yang paling tepat untuk melengkapi analogi:",
            subtestTemplateId: "1",
            options: [
              { id: "train-1-1-a", questionId: "train-1-1", text: "Mata", imageUrl: null, label: "A" },
              { id: "train-1-1-b", questionId: "train-1-1", text: "Telinga", imageUrl: null, label: "B" },
              { id: "train-1-1-c", questionId: "train-1-1", text: "Hidung", imageUrl: null, label: "C" },
              { id: "train-1-1-d", questionId: "train-1-1", text: "Mulut", imageUrl: null, label: "D" },
              { id: "train-1-1-e", questionId: "train-1-1", text: "Kepala", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-1-2",
            text: "Pilih lawan kata yang tepat:",
            subtestTemplateId: "1",
            options: [
              { id: "train-1-2-a", questionId: "train-1-2", text: "Besar", imageUrl: null, label: "A" },
              { id: "train-1-2-b", questionId: "train-1-2", text: "Tinggi", imageUrl: null, label: "B" },
              { id: "train-1-2-c", questionId: "train-1-2", text: "Kecil", imageUrl: null, label: "C" },
              { id: "train-1-2-d", questionId: "train-1-2", text: "Pendek", imageUrl: null, label: "D" },
              { id: "train-1-2-e", questionId: "train-1-2", text: "Lebar", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-1-3",
            text: "Pilih kata yang tidak termasuk dalam kelompok:",
            subtestTemplateId: "1",
            options: [
              { id: "train-1-3-a", questionId: "train-1-3", text: "Apel", imageUrl: null, label: "A" },
              { id: "train-1-3-b", questionId: "train-1-3", text: "Jeruk", imageUrl: null, label: "B" },
              { id: "train-1-3-c", questionId: "train-1-3", text: "Pisang", imageUrl: null, label: "C" },
              { id: "train-1-3-d", questionId: "train-1-3", text: "Wortel", imageUrl: null, label: "D" },
              { id: "train-1-3-e", questionId: "train-1-3", text: "Mangga", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-1-4",
            text: "Pilih kata yang paling tepat untuk melengkapi kalimat:",
            subtestTemplateId: "1",
            options: [
              { id: "train-1-4-a", questionId: "train-1-4", text: "Membaca", imageUrl: null, label: "A" },
              { id: "train-1-4-b", questionId: "train-1-4", text: "Menulis", imageUrl: null, label: "B" },
              { id: "train-1-4-c", questionId: "train-1-4", text: "Belajar", imageUrl: null, label: "C" },
              { id: "train-1-4-d", questionId: "train-1-4", text: "Mengajar", imageUrl: null, label: "D" },
              { id: "train-1-4-e", questionId: "train-1-4", text: "Mendengar", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-1-5",
            text: "Pilih kata yang memiliki arti sama:",
            subtestTemplateId: "1",
            options: [
              { id: "train-1-5-a", questionId: "train-1-5", text: "Cepat", imageUrl: null, label: "A" },
              { id: "train-1-5-b", questionId: "train-1-5", text: "Lambat", imageUrl: null, label: "B" },
              { id: "train-1-5-c", questionId: "train-1-5", text: "Gesit", imageUrl: null, label: "C" },
              { id: "train-1-5-d", questionId: "train-1-5", text: "Diam", imageUrl: null, label: "D" },
              { id: "train-1-5-e", questionId: "train-1-5", text: "Berhenti", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "2":
        // Subtest 2: Analogi Gambar (Radio Questions)
        return [
          {
            id: "train-2-1",
            text: "",
            subtestTemplateId: "2",
            options: [
              { id: "train-2-1-a", questionId: "train-2-1", text: "Segitiga", imageUrl: null, label: "A" },
              { id: "train-2-1-b", questionId: "train-2-1", text: "Lingkaran", imageUrl: null, label: "B" },
              { id: "train-2-1-c", questionId: "train-2-1", text: "Persegi", imageUrl: null, label: "C" },
              { id: "train-2-1-d", questionId: "train-2-1", text: "Jajar Genjang", imageUrl: null, label: "D" },
              { id: "train-2-1-e", questionId: "train-2-1", text: "Trapesium", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-2-2",
            text: "",
            subtestTemplateId: "2",
            options: [
              { id: "train-2-2-a", questionId: "train-2-2", text: "Matahari", imageUrl: null, label: "A" },
              { id: "train-2-2-b", questionId: "train-2-2", text: "Bulan", imageUrl: null, label: "B" },
              { id: "train-2-2-c", questionId: "train-2-2", text: "Bintang", imageUrl: null, label: "C" },
              { id: "train-2-2-d", questionId: "train-2-2", text: "Awan", imageUrl: null, label: "D" },
              { id: "train-2-2-e", questionId: "train-2-2", text: "Pelangi", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-2-3",
            text: "",
            subtestTemplateId: "2",
            options: [
              { id: "train-2-3-a", questionId: "train-2-3", text: "Mobil", imageUrl: null, label: "A" },
              { id: "train-2-3-b", questionId: "train-2-3", text: "Motor", imageUrl: null, label: "B" },
              { id: "train-2-3-c", questionId: "train-2-3", text: "Sepeda", imageUrl: null, label: "C" },
              { id: "train-2-3-d", questionId: "train-2-3", text: "Bus", imageUrl: null, label: "D" },
              { id: "train-2-3-e", questionId: "train-2-3", text: "Kereta", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-2-4",
            text: "",
            subtestTemplateId: "2",
            options: [
              { id: "train-2-4-a", questionId: "train-2-4", text: "Bunga", imageUrl: null, label: "A" },
              { id: "train-2-4-b", questionId: "train-2-4", text: "Pohon", imageUrl: null, label: "B" },
              { id: "train-2-4-c", questionId: "train-2-4", text: "Rumput", imageUrl: null, label: "C" },
              { id: "train-2-4-d", questionId: "train-2-4", text: "Daun", imageUrl: null, label: "D" },
              { id: "train-2-4-e", questionId: "train-2-4", text: "Akar", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-2-5",
            text: "",
            subtestTemplateId: "2",
            options: [
              { id: "train-2-5-a", questionId: "train-2-5", text: "Rumah", imageUrl: null, label: "A" },
              { id: "train-2-5-b", questionId: "train-2-5", text: "Gedung", imageUrl: null, label: "B" },
              { id: "train-2-5-c", questionId: "train-2-5", text: "Jembatan", imageUrl: null, label: "C" },
              { id: "train-2-5-d", questionId: "train-2-5", text: "Menara", imageUrl: null, label: "D" },
              { id: "train-2-5-e", questionId: "train-2-5", text: "Tembok", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "3":
        // Subtest 3: Analogi Verbal Lanjutan (Radio Questions)
        return [
          {
            id: "train-3-1",
            text: "Pilih kata yang melengkapi analogi: Kaki : Berjalan = Tangan : ?",
            subtestTemplateId: "3",
            options: [
              { id: "train-3-1-a", questionId: "train-3-1", text: "Memegang", imageUrl: null, label: "A" },
              { id: "train-3-1-b", questionId: "train-3-1", text: "Melihat", imageUrl: null, label: "B" },
              { id: "train-3-1-c", questionId: "train-3-1", text: "Mendengar", imageUrl: null, label: "C" },
              { id: "train-3-1-d", questionId: "train-3-1", text: "Mencium", imageUrl: null, label: "D" },
              { id: "train-3-1-e", questionId: "train-3-1", text: "Merasa", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-3-2",
            text: "Pilih kata yang melengkapi analogi: Air : Minum = Makanan : ?",
            subtestTemplateId: "3",
            options: [
              { id: "train-3-2-a", questionId: "train-3-2", text: "Minum", imageUrl: null, label: "A" },
              { id: "train-3-2-b", questionId: "train-3-2", text: "Makan", imageUrl: null, label: "B" },
              { id: "train-3-2-c", questionId: "train-3-2", text: "Memasak", imageUrl: null, label: "C" },
              { id: "train-3-2-d", questionId: "train-3-2", text: "Membeli", imageUrl: null, label: "D" },
              { id: "train-3-2-e", questionId: "train-3-2", text: "Menyimpan", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-3-3",
            text: "Pilih kata yang melengkapi analogi: Buku : Membaca = Musik : ?",
            subtestTemplateId: "3",
            options: [
              { id: "train-3-3-a", questionId: "train-3-3", text: "Mendengar", imageUrl: null, label: "A" },
              { id: "train-3-3-b", questionId: "train-3-3", text: "Melihat", imageUrl: null, label: "B" },
              { id: "train-3-3-c", questionId: "train-3-3", text: "Menyanyi", imageUrl: null, label: "C" },
              { id: "train-3-3-d", questionId: "train-3-3", text: "Menari", imageUrl: null, label: "D" },
              { id: "train-3-3-e", questionId: "train-3-3", text: "Memainkan", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-3-4",
            text: "Pilih kata yang melengkapi analogi: Matahari : Panas = Es : ?",
            subtestTemplateId: "3",
            options: [
              { id: "train-3-4-a", questionId: "train-3-4", text: "Dingin", imageUrl: null, label: "A" },
              { id: "train-3-4-b", questionId: "train-3-4", text: "Panas", imageUrl: null, label: "B" },
              { id: "train-3-4-c", questionId: "train-3-4", text: "Hangat", imageUrl: null, label: "C" },
              { id: "train-3-4-d", questionId: "train-3-4", text: "Segar", imageUrl: null, label: "D" },
              { id: "train-3-4-e", questionId: "train-3-4", text: "Basah", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-3-5",
            text: "Pilih kata yang melengkapi analogi: Guru : Mengajar = Dokter : ?",
            subtestTemplateId: "3",
            options: [
              { id: "train-3-5-a", questionId: "train-3-5", text: "Belajar", imageUrl: null, label: "A" },
              { id: "train-3-5-b", questionId: "train-3-5", text: "Mengobati", imageUrl: null, label: "B" },
              { id: "train-3-5-c", questionId: "train-3-5", text: "Membaca", imageUrl: null, label: "C" },
              { id: "train-3-5-d", questionId: "train-3-5", text: "Menulis", imageUrl: null, label: "D" },
              { id: "train-3-5-e", questionId: "train-3-5", text: "Mendengar", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "4":
        // Subtest 4: Klasifikasi (Text Questions)
        return [
          {
            id: "train-4-1",
            text: null,
            subtestTemplateId: "4",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "Tuliskan kata yang tidak termasuk dalam kelompok: Merah, Biru, Hijau, Kuning, Keras",
          },
          {
            id: "train-4-2",
            text: null,
            subtestTemplateId: "4",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "Tuliskan kata yang tidak termasuk dalam kelompok: Kucing, Anjing, Burung, Ikan, Meja",
          },
          {
            id: "train-4-3",
            text: null,
            subtestTemplateId: "4",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "Tuliskan kata yang tidak termasuk dalam kelompok: Senin, Selasa, Rabu, Kamis, Januari",
          },
          {
            id: "train-4-4",
            text: null,
            subtestTemplateId: "4",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "Tuliskan kata yang tidak termasuk dalam kelompok: Jakarta, Bandung, Surabaya, Medan, Indonesia",
          },
          {
            id: "train-4-5",
            text: null,
            subtestTemplateId: "4",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "Tuliskan kata yang tidak termasuk dalam kelompok: Mata, Telinga, Hidung, Mulut, Rambut",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "5":
        // Subtest 5: Aritmatika (Number Selection)
        return [
          {
            id: "train-5-1",
            text: "Berapa hasil dari 8 + 5?",
            subtestTemplateId: "5",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-5-2",
            text: "Berapa hasil dari 12 - 7?",
            subtestTemplateId: "5",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-5-3",
            text: "Berapa hasil dari 4 x 6?",
            subtestTemplateId: "5",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-5-4",
            text: "Berapa hasil dari 15 ÷ 3?",
            subtestTemplateId: "5",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-5-5",
            text: "Berapa hasil dari 9 + 3 x 2?",
            subtestTemplateId: "5",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "6":
        // Subtest 6: Deret Angka (Number Selection)
        return [
          {
            id: "train-6-1",
            text: "Lanjutkan pola: 2, 4, 6, 8, ?",
            subtestTemplateId: "6",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-6-2",
            text: "Lanjutkan pola: 1, 3, 5, 7, ?",
            subtestTemplateId: "6",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-6-3",
            text: "Lanjutkan pola: 3, 6, 9, 12, ?",
            subtestTemplateId: "6",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-6-4",
            text: "Lanjutkan pola: 10, 8, 6, 4, ?",
            subtestTemplateId: "6",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-6-5",
            text: "Lanjutkan pola: 1, 2, 4, 8, ?",
            subtestTemplateId: "6",
            options: undefined,
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "7":
        // Subtest 7: Analogi Gambar Lanjutan (Radio Questions with Images)
        return [
          {
            id: "train-7-1",
            text: "",
            subtestTemplateId: "7",
            options: [
              { id: "train-7-1-a", questionId: "train-7-1", text: "A", imageUrl: null, label: "A" },
              { id: "train-7-1-b", questionId: "train-7-1", text: "B", imageUrl: null, label: "B" },
              { id: "train-7-1-c", questionId: "train-7-1", text: "C", imageUrl: null, label: "C" },
              { id: "train-7-1-d", questionId: "train-7-1", text: "D", imageUrl: null, label: "D" },
              { id: "train-7-1-e", questionId: "train-7-1", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-7-2",
            text: "",
            subtestTemplateId: "7",
            options: [
              { id: "train-7-2-a", questionId: "train-7-2", text: "A", imageUrl: null, label: "A" },
              { id: "train-7-2-b", questionId: "train-7-2", text: "B", imageUrl: null, label: "B" },
              { id: "train-7-2-c", questionId: "train-7-2", text: "C", imageUrl: null, label: "C" },
              { id: "train-7-2-d", questionId: "train-7-2", text: "D", imageUrl: null, label: "D" },
              { id: "train-7-2-e", questionId: "train-7-2", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-7-3",
            text: "",
            subtestTemplateId: "7",
            options: [
              { id: "train-7-3-a", questionId: "train-7-3", text: "A", imageUrl: null, label: "A" },
              { id: "train-7-3-b", questionId: "train-7-3", text: "B", imageUrl: null, label: "B" },
              { id: "train-7-3-c", questionId: "train-7-3", text: "C", imageUrl: null, label: "C" },
              { id: "train-7-3-d", questionId: "train-7-3", text: "D", imageUrl: null, label: "D" },
              { id: "train-7-3-e", questionId: "train-7-3", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-7-4",
            text: "",
            subtestTemplateId: "7",
            options: [
              { id: "train-7-4-a", questionId: "train-7-4", text: "A", imageUrl: null, label: "A" },
              { id: "train-7-4-b", questionId: "train-7-4", text: "B", imageUrl: null, label: "B" },
              { id: "train-7-4-c", questionId: "train-7-4", text: "C", imageUrl: null, label: "C" },
              { id: "train-7-4-d", questionId: "train-7-4", text: "D", imageUrl: null, label: "D" },
              { id: "train-7-4-e", questionId: "train-7-4", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-7-5",
            text: "",
            subtestTemplateId: "7",
            options: [
              { id: "train-7-5-a", questionId: "train-7-5", text: "A", imageUrl: null, label: "A" },
              { id: "train-7-5-b", questionId: "train-7-5", text: "B", imageUrl: null, label: "B" },
              { id: "train-7-5-c", questionId: "train-7-5", text: "C", imageUrl: null, label: "C" },
              { id: "train-7-5-d", questionId: "train-7-5", text: "D", imageUrl: null, label: "D" },
              { id: "train-7-5-e", questionId: "train-7-5", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "8":
        // Subtest 8: Analogi Gambar Kompleks (Radio Questions with Images)
        return [
          {
            id: "train-8-1",
            text: "",
            subtestTemplateId: "8",
            options: [
              { id: "train-8-1-a", questionId: "train-8-1", text: "A", imageUrl: null, label: "A" },
              { id: "train-8-1-b", questionId: "train-8-1", text: "B", imageUrl: null, label: "B" },
              { id: "train-8-1-c", questionId: "train-8-1", text: "C", imageUrl: null, label: "C" },
              { id: "train-8-1-d", questionId: "train-8-1", text: "D", imageUrl: null, label: "D" },
              { id: "train-8-1-e", questionId: "train-8-1", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-8-2",
            text: "",
            subtestTemplateId: "8",
            options: [
              { id: "train-8-2-a", questionId: "train-8-2", text: "A", imageUrl: null, label: "A" },
              { id: "train-8-2-b", questionId: "train-8-2", text: "B", imageUrl: null, label: "B" },
              { id: "train-8-2-c", questionId: "train-8-2", text: "C", imageUrl: null, label: "C" },
              { id: "train-8-2-d", questionId: "train-8-2", text: "D", imageUrl: null, label: "D" },
              { id: "train-8-2-e", questionId: "train-8-2", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-8-3",
            text: "",
            subtestTemplateId: "8",
            options: [
              { id: "train-8-3-a", questionId: "train-8-3", text: "A", imageUrl: null, label: "A" },
              { id: "train-8-3-b", questionId: "train-8-3", text: "B", imageUrl: null, label: "B" },
              { id: "train-8-3-c", questionId: "train-8-3", text: "C", imageUrl: null, label: "C" },
              { id: "train-8-3-d", questionId: "train-8-3", text: "D", imageUrl: null, label: "D" },
              { id: "train-8-3-e", questionId: "train-8-3", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-8-4",
            text: "",
            subtestTemplateId: "8",
            options: [
              { id: "train-8-4-a", questionId: "train-8-4", text: "A", imageUrl: null, label: "A" },
              { id: "train-8-4-b", questionId: "train-8-4", text: "B", imageUrl: null, label: "B" },
              { id: "train-8-4-c", questionId: "train-8-4", text: "C", imageUrl: null, label: "C" },
              { id: "train-8-4-d", questionId: "train-8-4", text: "D", imageUrl: null, label: "D" },
              { id: "train-8-4-e", questionId: "train-8-4", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-8-5",
            text: "",
            subtestTemplateId: "8",
            options: [
              { id: "train-8-5-a", questionId: "train-8-5", text: "A", imageUrl: null, label: "A" },
              { id: "train-8-5-b", questionId: "train-8-5", text: "B", imageUrl: null, label: "B" },
              { id: "train-8-5-c", questionId: "train-8-5", text: "C", imageUrl: null, label: "C" },
              { id: "train-8-5-d", questionId: "train-8-5", text: "D", imageUrl: null, label: "D" },
              { id: "train-8-5-e", questionId: "train-8-5", text: "E", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      case "9":
        // Subtest 9: Klasifikasi Verbal (Radio Questions)
        return [
          {
            id: "train-9-1",
            text: "Pilih kata yang dimulai dengan huruf A:",
            subtestTemplateId: "9",
            options: [
              { id: "train-9-1-a", questionId: "train-9-1", text: "Anjing", imageUrl: null, label: "A" },
              { id: "train-9-1-b", questionId: "train-9-1", text: "Buku", imageUrl: null, label: "B" },
              { id: "train-9-1-c", questionId: "train-9-1", text: "Cinta", imageUrl: null, label: "C" },
              { id: "train-9-1-d", questionId: "train-9-1", text: "Dunia", imageUrl: null, label: "D" },
              { id: "train-9-1-e", questionId: "train-9-1", text: "Ekor", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
          {
            id: "train-9-2",
            text: "Pilih kata yang dimulai dengan huruf B:",
            subtestTemplateId: "9",
            options: [
              { id: "train-9-2-a", questionId: "train-9-2", text: "Anjing", imageUrl: null, label: "A" },
              { id: "train-9-2-b", questionId: "train-9-2", text: "Buku", imageUrl: null, label: "B" },
              { id: "train-9-2-c", questionId: "train-9-2", text: "Cinta", imageUrl: null, label: "C" },
              { id: "train-9-2-d", questionId: "train-9-2", text: "Dunia", imageUrl: null, label: "D" },
              { id: "train-9-2-e", questionId: "train-9-2", text: "Ekor", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 2,
            question: "",
          },
          {
            id: "train-9-3",
            text: "Pilih kata yang dimulai dengan huruf C:",
            subtestTemplateId: "9",
            options: [
              { id: "train-9-3-a", questionId: "train-9-3", text: "Anjing", imageUrl: null, label: "A" },
              { id: "train-9-3-b", questionId: "train-9-3", text: "Buku", imageUrl: null, label: "B" },
              { id: "train-9-3-c", questionId: "train-9-3", text: "Cinta", imageUrl: null, label: "C" },
              { id: "train-9-3-d", questionId: "train-9-3", text: "Dunia", imageUrl: null, label: "D" },
              { id: "train-9-3-e", questionId: "train-9-3", text: "Ekor", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 3,
            question: "",
          },
          {
            id: "train-9-4",
            text: "Pilih kata yang dimulai dengan huruf D:",
            subtestTemplateId: "9",
            options: [
              { id: "train-9-4-a", questionId: "train-9-4", text: "Anjing", imageUrl: null, label: "A" },
              { id: "train-9-4-b", questionId: "train-9-4", text: "Buku", imageUrl: null, label: "B" },
              { id: "train-9-4-c", questionId: "train-9-4", text: "Cinta", imageUrl: null, label: "C" },
              { id: "train-9-4-d", questionId: "train-9-4", text: "Dunia", imageUrl: null, label: "D" },
              { id: "train-9-4-e", questionId: "train-9-4", text: "Ekor", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 4,
            question: "",
          },
          {
            id: "train-9-5",
            text: "Pilih kata yang dimulai dengan huruf E:",
            subtestTemplateId: "9",
            options: [
              { id: "train-9-5-a", questionId: "train-9-5", text: "Anjing", imageUrl: null, label: "A" },
              { id: "train-9-5-b", questionId: "train-9-5", text: "Buku", imageUrl: null, label: "B" },
              { id: "train-9-5-c", questionId: "train-9-5", text: "Cinta", imageUrl: null, label: "C" },
              { id: "train-9-5-d", questionId: "train-9-5", text: "Dunia", imageUrl: null, label: "D" },
              { id: "train-9-5-e", questionId: "train-9-5", text: "Ekor", imageUrl: null, label: "E" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 5,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
  
      default:
        return [
          {
            id: "train-default-1",
            text: "Pertanyaan latihan default",
            subtestTemplateId: "1",
            options: [
              { id: "train-default-1-a", questionId: "train-default-1", text: "Pilihan A", imageUrl: null, label: "A" },
              { id: "train-default-1-b", questionId: "train-default-1", text: "Pilihan B", imageUrl: null, label: "B" },
              { id: "train-default-1-c", questionId: "train-default-1", text: "Pilihan C", imageUrl: null, label: "C" },
            ],
            imageUrl: undefined,
            createdAt: new Date(0),
            updatedAt: new Date(0),
            correctAnswer: null,
            order: 1,
            question: "",
          },
        ].filter(Boolean) as TrainingQuestion[];
    }
  };